version: '3'
services:
  app:
    image: 'node:19-slim'
    container_name: 'black-cat'
    ports:
      - '18080:18080/tcp'
    user: '1000:1000'
    working_dir: '/app'
    volumes:
      - './app:/app'
    command: 'node .'
    restart: 'unless-stopped'
